set pkgver.naps2=6.1.2
set ver.naps2=%pkgver.naps2%
set name.naps2=NAPS2 (Not Another PDF Scanner 2)
set exe.naps2=naps2-%ver.naps2%-setup.msi
set url.naps2="https://github.com/cyanfish/naps2/releases/download/v%ver.naps2/%exe.naps2%"
set arg.naps2=/quiet /norestart
set chk.naps2=%ProgramFiles(x86)%\NAPS2\NAPS2.exe
set regtext.naps2=Mozilla naps2
set regsearch.naps2=%uninstallreg32%
set followup.naps2=reg import "%filespath%!\naps2.reg"
set uninstall.naps2="%ProgramFiles(x86)%\NAPS2\unins000.exe" /SILENT
set regurl.naps2=https://github.com/cyanfish/naps2
set regexp.naps2=/html/body/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[2]/div/a/div/div[1]/span[1]
