set pkgver.spdf=3.4.6
set ver.spdf=%pkgver.spdf%
set name.spdf=Sumatra PDF
set exe.spdf=SumatraPDF-%pkgver.spdf%-64-install.exe
set url.spdf=https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/%pkgver.spdf%/%exe.spdf%
set arg.spdf=-s -all-users
set chk.spdf=%ProgramFiles%\SumatraPDF\SumatraPDF.exe
set regtext.spdf=SumatraPDF
set regsearch.spdf=%uninstallreg64%
set regurl.spdf=https://github.com/sumatrapdfreader/sumatrapdf/
set regexp.spdf=substring-before(/html/body/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[2]/div/a/div/div[1]/span[1],' ')
